version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db/fraud_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=fraud_db
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"

  flask-api:
    build:
      context: ./flask-api
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
